server:
  port: 8090

spring:
  application:
    name: application
  datasource:
    url: jdbc:mysql://localhost:3307/expenditure_management
    username: yascode
    password: yascode
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"